---
title: "index"
author: "Stefano"
date: "30 novembre 2017"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```




## Scatterplot

```{r scatterplot}
data(mpg)

g <- ggplot(mpg, aes(x = displ, y = hwy))
g + geom_point()

```

## `colors`

```{r colors}
g <- ggplot(mpg, aes(x = displ, y = hwy, color = class)) + 
  geom_point()
g

```
  
## Convert `colors` to `shape`
  
```{r b&w}
g <- ggplot(mpg, aes(x = displ, y = hwy, shape = class)) + 
  geom_point()
g

```

## Shape Size

```{r shape size}
ggplot(mpg, aes(x = cty, y = hwy, size = class , color = fl)) + 
  geom_point(alpha = .4)

```




```{r color 2}
ggplot(mpg, aes(x = cty, y = hwy, size = class)) + 
  geom_point(alpha = .4, color = "blue")

```



```{r color 3}
 ggplot(data = mpg) + 
      geom_point(aes(x = displ, y = hwy), color = "blue")

```

```{r continue variable}
 ggplot(mpg, aes(x = displ, y = hwy, color = cty)) + 
      geom_point()

```

```{r subset}
 ggplot(mpg, aes(x = displ, y = hwy, color = displ < 5)) + 
      geom_point()
```


```{r geom_examples}
 ggplot(mpg, aes(x = drv, y = hwy)) + 
      geom_boxplot()
```


```{r multiple geom}
 ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point(color = "blue") +
  geom_smooth(method = "lm") +
  geom_smooth(method = "loess", color = "red") +
  ggtitle("Scatter plot") +
  xlab("Engine Displacement") +
  ylab("Highway") +
  theme_bw()+
  theme(text = element_text(size = 8),line = element_line(size = .4))+
  facet_wrap(~factor(class), scales = "free")
  
  
  
  
```


## Data Wrangling with `dplyr`

```{r 1}
gapminder <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

head(gapminder, 10)
tail(gapminder)
str(gapminder)
names(gapminder)
dim(gapminder)
ncol(gapminder)
summary(gapminder)

```


```{r 2}
filter(gapminder,lifeExp < 29)

filter(gapminder, country == "Mexico")

mean(filter(gapminder, country=="Sweden")$lifeExp)

gapminder %>% head()


g <- filter(gapminder, country=="Sweden")
mean(g)

gapminder  %>%  
  filter(country == "Sweden")  %>% 
  summarize(mean_lifeExp = mean(lifeExp))
```







